# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 284bf25bf974ef9ab680bb41d2f9cdc3eef2d9a117b7f25678df93f135cfeb6005e49bca324b3d493e76e03f09dfb886bcce1503013a147b88b2b987b5b3f22d

test:
  secret_key_base: e902406cba2a73621ea08349283bb121e04f2a9a0751baadc1badcaaef75c531334d19b04ac400cb4f277d79b49f1dc366affc840c23bb93a0f714ea0b46a6c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
